ureportdb:
    image: "postgres:9.4"

ureportredis:
    image: "redis"

ureport:
  build: .
  volumes:
      - ./:/code
  environment:
      RDS_HOSTNAME: "ureportdb"
      RDS_USERNAME: "postgres"
      RDS_PASSWORD: ""
      RDS_PORT: ""
      RDS_DB_NAME: "ureport"
      REDISHOST: "ureportredis"
      STATIC_DIR: "/var/www/static/"
      HOSTNAME: "ureport-local.eocng.org"
  command: start 
  ports:
    - "4000:5000"
    - "8000:8000"
  links:
    - ureportdb
    - ureportredis
