branch-defaults:
  default:
    environment: ureport-stage
  master:
    environment: ureport-stage
  develop:
    environment: ureport-stage
global:
  application_name: ureport
  default_ec2_keyname: aws-deploy
  default_platform: 64bit Amazon Linux 2015.09 v2.0.6 running Multi-container Docker
    1.7.1 (Generic)
  default_region: eu-central-1
  profile: null
  sc: git
deploy:
    artifact: conf/deploy.zip
